# Generated by Django 4.2.3 on 2023-11-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajetoria',
            fields=[
                ('Nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='trumb_trajetoria')),
                ('Descricao', models.TextField(max_length=1000)),
                ('Categoria', models.CharField(choices=[('historia01', 'HISTORIA01'), ('historia02', 'HISTORIA02'), ('historia03', 'HISTORIA03'), ('OUTROS', 'Outros')], max_length=15)),
                ('AnoInicial', models.DateField(blank=True, null=True)),
                ('CodigoTrajetoria', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.etapa')),
            ],
        ),
        migrations.DeleteModel(
            name='ana',
        ),
    ]
