# Generated by Django 4.2.3 on 2023-11-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_material_etapa_idmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Assunto',
            new_name='assunto',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='DataPublicação',
            new_name='dataPublicação',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Fonte',
            new_name='fonte',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='IdMaterial',
            new_name='idMaterial',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Tipo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='trajetoria',
            old_name='AnoInicial',
            new_name='anoInicial',
        ),
        migrations.RenameField(
            model_name='trajetoria',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='trajetoria',
            old_name='CodigoTrajetoria',
            new_name='codigoTrajetoria',
        ),
        migrations.RenameField(
            model_name='trajetoria',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='trajetoria',
            old_name='Nome',
            new_name='nome',
        ),
    ]
