# Generated by Django 4.2.3 on 2023-11-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_usuario_rename_assunto_material_assunto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.etapa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usuario')),
            ],
        ),
    ]
