# Generated by Django 4.2.3 on 2023-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_historico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='fonte',
        ),
        migrations.AddField(
            model_name='material',
            name='fonteform',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='fontejogo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='fontepdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='fontevideo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
