# Generated by Django 4.2.3 on 2023-12-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_trajetoria_etapa_etapa_trajetoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajetoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
